import Head from 'next/head'
import Image from 'next/image'

import Nav from '../components/Nav/Nav'
import HomePage from '../components/Home/HomePage'
import { AppProvider } from '../context'
import SideMenu from '../components/SideMenu'
import Sign from '../components/Sign/Sign'
export default function Home() {
  return (
    <AppProvider>
      <div>
        <Head>
          <title>Js Innovations</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Nav />
        <HomePage />
        <SideMenu />
        <Sign />
      </div>
    </AppProvider>
  )
}
